version: "3.9"

services:
  masterclasses-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: masterclasses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/db/masterclasses.sql:/docker-entrypoint-initdb.d/masterclasses.sql:ro

  users-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./scripts/db/users.sql:/docker-entrypoint-initdb.d/users.sql:ro

